policy_kwargs:
  batch_size: 32
  buffer_size: 50000
  combined_sampling: false
  dqn_kwargs: {}
  exploration_rate: 0.05
  fisher_gamma: 0.99
  fisher_num_batches: 100
  fisher_lambda: 25 # Try [1, 25, 50, 100, 500] original paper used 400 with Atari
  handle_timeout_termination: false
  learning_rate: 0.0001
  loss_kwargs:
    discount_factor: 0.99
    reward_clipping_func:
      _partial_: true
      _target_: torch.clamp
      max: 1
      min: -1
  loss_name: dqn
  optimize_memory_usage: true
  optimizer_class: null
  render_collection_freq: null
  reset_buffer: false
  reset_optimizer: false
  save_replay_buffer: true
  target_update_frequency: 10000
  timesteps_per_collection: 4
  timesteps_per_save: ${exp.num_timesteps}
  track_task_id: true
  update_after: null
policy_struct:
  _target_: continual_rl.available_policies.PolicyStruct
  config:
    _target_: hydra.utils.get_class
    path: crl.policies.ewc.ewc_dqn_policy_config.EWCDQNPolicyConfig
  policy:
    _target_: hydra.utils.get_class
    path: crl.policies.ewc.ewc_dqn_policy.EWCDQNPolicy