num_timesteps: 300000
num_tasks: ${eval:'len(${.exp_loader.task_func_kwargs})'}
max_episode_steps: 5000
ple_kwargs:
  display_screen: False
  force_fps: True
  reward_values:
    positive: 1.0
    negative: -1.0
    tick: 0.0
    loss: 0.0
    win: 0.0
name: catcher

exp_loader:
  _target_: crl.experiment_loader.exp_loader

  task_func:
    _partial_: True
    _target_: crl.experiments.make_ple.get_single_ple_task

  task_func_kwargs:
    - num_timesteps: ${task_seq.num_timesteps}
      max_episode_steps: ${task_seq.max_episode_steps}
      env_kwargs:
        game_kwargs:
          fall_speed_modifier: 0
        ple_kwargs: ${task_seq.ple_kwargs}

  game_names:
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualCatcher
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualCatcher
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualCatcher
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualCatcher
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualCatcher

  exp_kwargs:
    continual_testing_freq: ${eval:${task_seq.num_timesteps}//30}
    cycle_count: 1