num_timesteps: 25000
num_tasks: ${eval:'len(${.exp_loader.task_func_kwargs})'}
max_episode_steps: 5000
ple_kwargs:
  display_screen: False
  force_fps: True
  reward_values:
    positive: 1.0
    negative: 0.0
    tick: 0.0
    loss: -1.0
    win: 0.0
name: flappy

exp_loader:
  _target_: crl.experiment_loader.exp_loader

  task_func:
    _partial_: True
    _target_: crl.experiments.make_ple.get_single_ple_task
    num_timesteps: ${task_seq.num_timesteps}
    max_episode_steps: ${task_seq.max_episode_steps}
    continual_eval_num_returns: 10

  task_func_kwargs:
    - env_kwargs:
        game_kwargs:
          pipe_gap_modifier: 0
        ple_kwargs: ${task_seq.ple_kwargs}
    - env_kwargs:
        game_kwargs:
          pipe_gap_modifier: 1
        ple_kwargs: ${task_seq.ple_kwargs}
    - env_kwargs:
        game_kwargs:
          pipe_gap_modifier: 2
        ple_kwargs: ${task_seq.ple_kwargs}
    - env_kwargs:
        game_kwargs:
          pipe_gap_modifier: 3
        ple_kwargs: ${task_seq.ple_kwargs}
    - env_kwargs:
        game_kwargs:
          pipe_gap_modifier: 4
        ple_kwargs: ${task_seq.ple_kwargs}

  game_names:
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualFlappyBird
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualFlappyBird
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualFlappyBird
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualFlappyBird
    - _target_: hydra.utils.get_class
      path: crl.common.envs.ple_envs.ContinualFlappyBird

  exp_kwargs:
    continual_testing_freq: ${eval:${task_seq.num_timesteps}//5}
    cycle_count: 4