from pdb import set_trace
from copy import deepcopy

import torch
from torch import nn

from crl.policies.dqn.dqn_policy import DQNPolicy
from crl.policies.mer.mer_dqn_policy_config import MERDQNPolicyConfig

class MERDQNPolicy(DQNPolicy):
    """DQN trained with Meta-Experience Replay (MER), using nested Reptile meta-updates to reduce interference.

    Instead of a single gradient step per training call, `train` runs
    `cfg.steps` inner iterations (each doing a Reptile "within-batch" update
    after training on one sampled batch), then applies an outer "across-batch"
    Reptile update over all inner iterations combined. This encourages
    parameter updates that generalize across the sampled batches rather than
    overfitting to any single one.
    """

    def __init__(self, config: MERDQNPolicyConfig, observation_space, action_spaces):
        """
        Args:
            config: Policy configuration, including MER-specific
                hyperparameters (`within_batch_beta`, `across_batch_gamma`,
                `steps`, `online`).
            observation_space: Gym observation space, shared across tasks.
            action_spaces: Dict mapping action_space_id to a Gym action space;
                all must have the same `.shape`.
        """
        super().__init__(config, observation_space, action_spaces)

    def _reptile_update(self, weights_before, weights_after, scaling_factor):
        """Interpolates from `weights_before` towards `weights_after` by `scaling_factor` (Reptile meta-update).

        Closely follows https://github.com/mattriemer/MER/blob/master/model/meralg7.py.

        Args:
            weights_before: State dict of parameters before the inner update(s).
            weights_after: State dict of parameters after the inner update(s).
            scaling_factor: Interpolation factor (e.g. `cfg.within_batch_beta`
                or `cfg.across_batch_gamma`); 1.0 fully adopts `weights_after`,
                0.0 keeps `weights_before`.

        Returns:
            Tuple `(new_state_dict, avg_abs_diff)`: the interpolated state
            dict, and the mean absolute parameter change (for logging).
        """
        total_diff = 0
        total_params = 0
        new_state_dict = {}
        
        for name in weights_before:
            param_diff = weights_after[name] - weights_before[name]
            new_state_dict[name] = weights_before[name] + (param_diff * scaling_factor) 
            
            total_diff += torch.sum(torch.abs(param_diff))
            total_params += len(param_diff)
                
        return new_state_dict, total_diff.detach().item() / total_params

    def train(self, storage_buffer):
        """Runs the MER nested-Reptile training loop: inner within-batch updates, then an outer across-batch update.

        For `cfg.steps` iterations: samples a batch, computes the DQN loss
        (either per-sample if `cfg.online`, or on the full batch), takes a
        gradient step, then Reptile-interpolates the resulting weights back
        towards the pre-iteration weights (the "within" update). After all
        iterations, Reptile-interpolates the final weights back towards the
        weights from before training began (the "across" update).

        Based on https://github.com/mattriemer/MER/blob/master/model/meralg1.py.

        Args:
            storage_buffer: Samples collected since `train()` was last called.
                Unused here (data was already added to the replay buffer by
                `DQNPolicy._compute_training_action`); generated by the
                `EnvironmentRunner`.

        Returns:
            A list of Tensorboard-style log dicts (per-step loss and
            within-batch diff, plus the final across-batch diff), or None if
            there weren't yet enough samples in the replay buffer to train.
        """
        logs = []
        if not self.replay_buffer.full and self.cfg.update_after >= self.replay_buffer.pos:
            self.logger.debug(f"{self.total_timesteps} Only {len(self.replay_buffer)} samples, need {self.cfg.update_after} samples before training")
            return

        # Copy parameters for across difference
        # Will require grad but shouldn't be updated as parameters are
        # deep copied and not passed to the optimizer.
        across_params = deepcopy(self.dqn.state_dict())
        
        # Sample from replay buffer for so many steps (typically set 1 for RL)
        for s in range(self.cfg.steps):
            self.optimizer.zero_grad()
            # Sample from replay buffer
            replay_samples = self.replay_buffer.sample(
                batch_size=self.cfg.batch_size,
                combined=self.cfg.combined_sampling,
            )
            
            # Copy parameters for between difference
            within_params = deepcopy(self.dqn.state_dict())
            
            # Update loss using gradient for each sample
            
            if self.cfg.online:
                loss = 0
                for i in range(len(replay_samples)):
                    # Wrap a single sample in replay sample class
                    single_sample = self.replay_buffer.sample_class(*replay_samples[[i]])
                    # Compute DQN replay loss using a single sample
                    loss_i, _ = self._compute_loss(single_sample)

                    # Update network
                    loss_i.backward()
                    self.optimizer.step()
                    loss += loss_i.detach()
                loss /= len(replay_samples)
            else:
                loss, _ = self._compute_loss(replay_samples)
                loss.backward()
                self.optimizer.step()
            logs.append({"type": "scalar", "tag": f"step{s}_loss", "value": loss.item()})
            
            # Update params within (for each replay batch)
            within_stat_dict, within_avg_diff = self._reptile_update(
                weights_before=within_params,
                weights_after=self.dqn.state_dict(), 
                scaling_factor=self.cfg.within_batch_beta
            )
            self.dqn.load_state_dict(within_stat_dict)
            logs.append({"type": "scalar", "tag": f"step{s}_within_diff", "value": within_avg_diff})
            
        # Update params across (once all replay batches have been used for updating)
        across_stat_dict, across_avg_diff = self._reptile_update(
            weights_before=across_params, 
            weights_after=self.dqn.state_dict(),
            scaling_factor=self.cfg.across_batch_gamma
        )
        self.dqn.load_state_dict(across_stat_dict)
        logs.append({"type": "scalar", "tag": "across_diff", "value": across_avg_diff})

        return logs